Repository ichatzivasileiadou/SDiP-Hissssteria, pull requests merged in 2025-04, with the labels that each got.

#31 feat:add manhattan distance calculation functionality
  index.js
  manhattan-food.js
Labels: enhancement

#32 feat: add head to head functionality
  head-to-head-mov.js
  index.js
Labels: enhancement

#33 chore: add and configure editorconfig
  .editorconfig
Labels: chore

#35 Add Prettier with default configuration
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
Labels: chore

#37 chore: add and configure eslint
  eslint.config.js
  head-to-head-mov.js
  index.js
  manhattan-food.js
  package-lock.json
  package.json
  server.js
Labels: chore

#38 docs: Update changelog with new features and changes
  .documentation/CHANGELOG.md
Labels: documentation
