Repository ichatzivasileiadou/SDiP-Hissssteria, pull requests merged in 2025-05, with the labels that each got.

#48 chore: setup jest and eslint-jest-plugin test suites
  eslint.config.js
  index.js
  jest.config.js
  package-lock.json
  package.json
  snakes-movement-to-tail.js
  sum.js
  sum.test.js
Labels: chore

#49 feat: Add flood fill algorithm and integrate it into snake movement logic
  floodFill/floodFill.js
  index.js
  tests/floodFill.test.js
Labels: enhancement

#50 feat: Reach at least 50% test coverage
  head-to-head-mov.js
  manhattan-food.js
  package-lock.json
  package.json
  snakes-movement-to-tail.js
  tests/head-to-head-mov.test.js
  tests/manhattan-food.test.js
  tests/snakes-movement-to-tail.test.js
  tests/sum.test.js
Labels: enhancement, testing

#51 hotfix: alter snake's customisation
  index.js
Labels: enhancement, hotfix

#52 fix: backport hotfix v1.0.1 to develop
  index.js
Labels: enhancement, hotfix

#54 Release: v1.1.0
  .documentation/CHANGELOG.md
  eslint.config.js
  floodFill/floodFill.js
  head-to-head-mov.js
  index.js
  jest.config.js
  manhattan-food.js
  package-lock.json
  package.json
  snakes-movement-to-tail.js
  sum.js
  tests/floodFill.test.js
  tests/head-to-head-mov.test.js
  tests/manhattan-food.test.js
  tests/snakes-movement-to-tail.test.js
  tests/sum.test.js
Labels: release
